script: 
    - bin/trix --matrix matrix_travis --env "$TRIX_ENV" run test/matrix.sh
matrix:
    include:
       - env: TRIX_ENV="env_travis_linux env_common_bash"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_common_busybox_sh"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_common_dash"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_extras_bash2_05b"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_extras_bash3_0_16"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_extras_bash3_2_48"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_extras_bash4_2_45"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_extras_zsh_beta"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_shell_ksh"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_shell_mksh"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_shell_pdksh"
         os:  linux 
       - env: TRIX_ENV="env_travis_linux env_shell_zsh"
         os:  linux 
       - env: TRIX_ENV="env_travis_osx env_common_bash"
         os:  osx 
       - env: TRIX_ENV="env_travis_osx env_shell_ksh"
         os:  osx 
       - env: TRIX_ENV="env_travis_osx env_shell_mksh"
         os:  osx 
       - env: TRIX_ENV="env_travis_osx env_shell_zsh"
         os:  osx 
